"""create_initial_tables

Revision ID: d2f7cad1aa29
Revises: 
Create Date: 2026-04-05 18:36:49.740736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f7cad1aa29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE INDEX idx_iocs_validated ON iocs (submitted_at DESC) WHERE status = 'validated';")
    op.execute("CREATE INDEX idx_iocs_category ON iocs (threat_category);")
    op.execute("CREATE INDEX idx_iocs_submitted_at ON iocs (submitted_at DESC);")
    op.execute("CREATE INDEX idx_iocs_enrichment_gin ON iocs USING GIN (enrichment_json);")
    # ### end Alembic commands ###
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
