"""create_initial_tables

Revision ID: dc5689c2bf86
Revises: 841eb27834b7
Create Date: 2026-04-05 18:26:31.849802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc5689c2bf86'
down_revision: Union[str, Sequence[str], None] = '841eb27834b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('siret', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=False),
    sa.Column('api_key_salt', sa.String(length=32), nullable=False),
    sa.Column('trust_score', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('siret')
    )
    op.create_table('iocs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('IP', 'URL', 'HASH', 'EMAIL', name='ioctype'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('danger_score', sa.SmallInteger(), nullable=True),
    sa.Column('threat_category', sa.String(length=50), nullable=True),
    sa.Column('enrichment_js', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_feature_importances', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VALIDaTED', 'REJECTED', name='iocstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blockchain_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ioc_id', sa.UUID(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ioc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blockchain_records')
    op.drop_table('iocs')
    op.drop_table('organisations')
    # ### end Alembic commands ###
